#!/bin/bash

function usage {
  echo "Usage:"
  echo "         elixirsips-downloader FROM TO"
}

FROM=$1
TO=$2

if [[ -z "$FROM" || -z "$TO" ]]; then
  usage
  exit 1
fi

es_parse_episodes > elixirsips_episodes.txt

if grep -q "not logged in" "$File"; then
  echo "It seems you're not logged in, please read the manual online at https://www.npmjs.com/package/elixirsips-downloader"
  exit 1
fi

P="p"
SED_PARAMS="-n $FROM,$TO$P"
sed $SED_PARAMS elixirsips_episodes.txt | es_parse_attachments | es_get_attachments

rm elixirsips_episodes.txt
